# docker-compose.yml
services:
  nginx:
    image: nginx:latest
    ports:
      - "8082:80"
    volumes:
      - ./php/src:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database  
    networks:
      - nimon-net

  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    working_dir: /var/www/html
    volumes:
      - ./php/src:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      - database  
    networks:
      - nimon-net

  database:     
    image: postgres:latest
    environment:
      POSTGRES_DB: nimonspedia
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - nimon-net
    
volumes:
  db-data:

networks:
  nimon-net:
    driver: bridge